django_quickblocks/urls.py
from .views import *

urlpatterns = QuickBlockCRUDL().as_urlpatterns()
urlpatterns += QuickBlockTypeCRUDL().as_urlpatterns()
urlpatterns += QuickBlockImageCRUDL().as_urlpatterns()

django_quickblocks/models.py
from django.db import models
from django.contrib.auth.models import User
from smartmin.models import SmartModel

class QuickBlockType(SmartModel):
    """
    Quick Block Types just group fields by a slug.. letting you do lookups by type.  In the future
    it may be nice to specify which fields should be displayed when creating fields of a new type.
    """
    name = models.CharField(max_length=75, unique=True,
                            help_text="The human readable name for this content type")
    slug = models.SlugField(max_length=50, unique=True,
                            help_text="The slug to idenfity this content type, used with the template tags")
    description = models.TextField(blank=True, null=True,
                                   help_text="A description of where this content type is used on the site and how it will be dsiplayed")

    has_title = models.BooleanField(default=True,
                                    help_text="Whether this content should include a title")
    has_image = models.BooleanField(default=True,
                                    help_text="Whether this content should include an image")
    has_rich_text = models.BooleanField(default=True,
                                        help_text="Whether this content should use a rich HTML editor")
    has_summary = models.BooleanField(default=True,
                                      help_text="Whether this content should include a summary field")
    has_link = models.BooleanField(default=True,
                                   help_text="Whether this content should include a link")
    has_gallery = models.BooleanField(default=False,
                                      help_text="Whether this content should allow upload of additional images, ie a gallery")
    has_color = models.BooleanField(default=False,
                                    help_text="Whether this content has a color field")
    has_video = models.BooleanField(default=False,
                                    help_text="Whether this content should allow setting a YouTube id")
    has_tags = models.BooleanField(default=False,
                                   help_text="Whether this content should allow tags")

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class QuickBlock(SmartModel):
    """
    A QuickBlock is just a block of content, organized by type and priority.  All fields are optional
    letting you use them for different things.
    """
    quickblock_type = models.ForeignKey(QuickBlockType, on_delete=models.PROTECT,
                                        verbose_name="Content Type",
                                        help_text="The category, or type for this content block")

    title = models.CharField(max_length=255, blank=True, null=True,
                             help_text="The title for this block of content, optional")
    summary = models.TextField(blank=True, null=True,
                               help_text="The summary for this item, should be short")
    content = models.TextField(blank=True, null=True,
                               help_text="The body of text for this content block, optional")
    image = models.ImageField(blank=True, null=True, upload_to='quickblocks',
                              help_text="Any image that should be displayed with this content block, optional")
    color = models.CharField(blank=True, null=True, max_length=16, 
                            help_text="A background color to use for the image, in the format: #rrggbb")
    link = models.CharField(blank=True, null=True, max_length=255,
                            help_text="Any link that should be associated with this content block, optional")
    video_id = models.CharField(blank=True, null=True, max_length=255,
                                help_text="The id of the YouTube video that should be linked to this item")
    tags = models.CharField(blank=True, null=True, max_length=255,
                           help_text="Any tags for this content block, separated by spaces, can be used to do more advanced filtering, optional")
    priority = models.IntegerField(default=0,
                                   help_text="The priority for this block, higher priority blocks come first")


    def space_tags(self):
        """
        If we have tags set, then adds spaces before and after to allow for SQL querying for them.
        """
        if self.tags and self.tags.strip():
            self.tags = " " + self.tags.strip().lower() + " "

    def sorted_images(self):
        return self.images.filter(is_active=True).order_by('-priority')        

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class QuickBlockImage(SmartModel):
    quickblock = models.ForeignKey(QuickBlock, on_delete=models.PROTECT, related_name='images')
    image = models.ImageField(upload_to='quickblock_images/', width_field="width", height_field="height")
    caption = models.CharField(max_length=64)
    priority = models.IntegerField(default=0, blank=True, null=True)
    width = models.IntegerField()
    height = models.IntegerField()

    def __unicode__(self):
        return self.image.url

    def __str__(self):
        return self.image.url

django_quickblocks/templates/django_quickblocks/quickblock_create.html
{% extends "django_quickblocks/quickblock_form.html" %}

django_quickblocks/templates/django_quickblocks/quickblock_form.html
{% extends "smartmin/form.html" %}
{% load thumbnail %}

{% block extra-fields %}
{% if object and type.has_gallery %}
<div class="form-group ">
  <label class="col-sm-2 control-label" for="">Gallery</label>
  <div class="col-sm-10">
    {% for img in object.sorted_images %}
    {% thumbnail img.image "100x100" crop="center" as im %}
    <a href="{% url 'django_quickblocks.quickblockimage_update' img.id %}"><img class="thumb" src="{{ im.url }}" width="{{ img.x }}" height="{{ img.y }}" /></a>
    {% endthumbnail %}
    {% endfor %}
    <a class="btn btn-default btn-small" href="{% url 'django_quickblocks.quickblockimage_create' %}?quickblock={{ object.id }}">Add Image</a>
  </div>
</div>
{% endif %}
{% endblock %}


{% block extra-style %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/prettify.css"></link>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap3-wysihtml5.min.css"></link>
<style>
{% if type.has_rich_text %}
#id_content {
  width: 93%;
  height: 250px;
  margin-right: 20px;
}
#id_summary {
  width: 93%;
  height: 150px;
  margin-right: 20px;
}

label.checkbox {
  padding-left: 20px;
}

{% endif %}
img.thumb {
  margin: 5px;
  border: 1px solid #ccc;
}
</style>
{% endblock %}

{% block extra-script %}
<script src="{{ STATIC_URL }}js/wysihtml5-advanced.js"></script>
<script src="{{ STATIC_URL }}js/prettify.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap3-wysihtml5.all.min.js"></script>

<script>
{% if type.has_rich_text %}
$(function(){
  $("#id_content").wysihtml5({
    parserRules: wysihtml5ParserRules,
    "font-styles": true,
    color: true,
    html: true,  
    image: false,                             
{% if user.is_superuser or perms.django_quickblocks.quickblock_html %}                            
    html: true,
{% else %}
    html: false,
{% endif %}
    stylesheets: ["{{ STATIC_URL }}css/wysiwyg-color.css"], 
  });
  $("#id_summary").wysihtml5({
    "font-styles": true,
    color: true,
    html: true,  
    image: false,                             
{% if user.is_superuser %}                            
    html: true,
{% else %}
    html: false,
{% endif %}
    stylesheets: ["{{ STATIC_URL }}css/wysiwyg-color.css"], 
  });
});
{% endif %}
</script>
{% endblock %}

django_quickblocks/templates/django_quickblocks/quickblock_list.html
{% extends "smartmin/list.html" %}

{% block search-form %}
<form class="form-inline" role="form">
  <select name="type" style="width:180px;margin-bottom:0px" class="form-control">
    <option value="0" {% if filtered_type == 0 %}selected{%endif%}>-----</option>
    {% for type in types %}
    <option value="{{ type.id }}" {% if filtered_type.id == type.id %}selected{%endif%}>{{ type.name }}</option>
    {% endfor %}
  </select>
  <input type="text" class="input-medium search-query form-control" name="search" value="{{ search }}">
  <button type="submit" class="btn btn-default">Search</button>
</form>
{% endblock %}


{% block table-buttons %}
<div class="pull-right">
  <form class="form-inline" action="{% url 'django_quickblocks.quickblock_create' %}" method="get" >
    <select name="type" style="width:180px;margin-bottom:0px" class="form-control">
    {% for type in types %}
      <option value="{{ type.id }}" {% if filtered_type.id == type.id %}selected{%endif%}>{{ type.name }}</option>
    {% endfor %}
    </select>
    <button class="btn btn-primary" type="submit" value="Add" name="Add">Add</button>
  </form>
</div>
{% endblock %}

django_quickblocks/templates/django_quickblocks/quickblock_update.html
{% extends "django_quickblocks/quickblock_form.html" %}